<a href="https://colab.research.google.com/github/MohammadrezaTale/EDA-for-Datasets/blob/main/Global_Marine_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Global Marine Data
####Historical marine data are comprised of ship, buoy, and platform observations from 1662-present. Data values are delayed by one month. In addition to location, ship identification, ship speed, and ship direction, weather elements observed include: wind direction and speed, visibility, present and past weather, sea level pressure, dry bulb, wet bulb, and dew point temperatures, sea surface temperature, cloud data, wave data, and ice accretion.

##import packages and Dataset

In [93]:
#import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [9]:
#import dataset
!gdown --id 1BwK9PrRoK9400LEFU-WFVyP6xu2QIhIt
df = pd.read_csv('Marine_CSV_sample.csv')

/usr/local/lib/python3.11/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1BwK9PrRoK9400LEFU-WFVyP6xu2QIhIt
To: /content/Marine_CSV_sample.csv
100% 7.02k/7.02k [00:00<00:00, 16.1MB/s]

,Identification,Latitude,Longitude,Time of Observation,Ice Accretion On Ship,Thickness of Ice Accretion On Ship,Rate of Ice Accretion on Ship,Sea Level Pressure,Characteristics of Pressure Tendency,Pressure Tendency,...,Cloud Height Indicator,Cloud Height,Middle Cloud Type,High Cloud Type,Visibility,Visibility Indicator,Present Weather,Past Weather,Wind Direction,Wind Speed
0,D5GN6,-35.8,2.9,2015-01-12T00:00:00,,,,29.83,8,0.0,...,,5,,,97,,3,2,300,139
1,D5GN6,-35.9,6.9,2015-01-12T12:00:00,,,,29.93,1,0.0,...,,2,1,A,97,,2,2,180,165
2,D5GN6,-35.9,8.6,2015-01-12T18:00:00,,,,30.02,1,0.0,...,,2,0,0,97,,2,2,170,154
3,D5GN6,-35.7,11.9,2015-01-13T06:00:00,,,,30.14,0,0.0,...,,3,0,0,98,,1,2,140,118
4,D5GN6,-35.6,13.7,2015-01-13T12:00:00,,,,30.12,8,,...,,5,7,A,98,,2,1,160,123

##Data examination

In [10]:
df.head()

,Identification,Latitude,Longitude,Time of Observation,Ice Accretion On Ship,Thickness of Ice Accretion On Ship,Rate of Ice Accretion on Ship,Sea Level Pressure,Characteristics of Pressure Tendency,Pressure Tendency,...,Cloud Height Indicator,Cloud Height,Middle Cloud Type,High Cloud Type,Visibility,Visibility Indicator,Present Weather,Past Weather,Wind Direction,Wind Speed
0,D5GN6,-35.8,2.9,2015-01-12T00:00:00,,,,29.83,8,0.0,...,,5,,,97,,3,2,300,139
1,D5GN6,-35.9,6.9,2015-01-12T12:00:00,,,,29.93,1,0.0,...,,2,1,A,97,,2,2,180,165
2,D5GN6,-35.9,8.6,2015-01-12T18:00:00,,,,30.02,1,0.0,...,,2,0,0,97,,2,2,170,154
3,D5GN6,-35.7,11.9,2015-01-13T06:00:00,,,,30.14,0,0.0,...,,3,0,0,98,,1,2,140,118
4,D5GN6,-35.6,13.7,2015-01-13T12:00:00,,,,30.12,8,,...,,5,7,A,98,,2,1,160,123

In [11]:
df.shape

(55, 33)

In [12]:
df.describe()

        Latitude  Longitude  Visibility  Wind Direction  Wind Speed
count  55.000000  55.000000   55.000000       55.000000   55.000000
mean  -20.558182  51.829091   97.527273      161.127273  108.345455
std    13.168181  27.141806    0.503857       99.436757   69.483336
min   -35.900000   2.900000   97.000000       20.000000   10.000000
25%   -32.300000  29.000000   97.000000       90.000000   69.500000
50%   -23.900000  51.200000   98.000000      140.000000  108.000000
75%   -11.200000  75.950000   98.000000      215.000000  139.000000
max     6.100000  94.600000   98.000000      362.000000  463.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 33 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Identification                        55 non-null     object
 1   Latitude                              55 non-null     float64
 2   Longitude                             55 non-null     float64
 3   Time of Observation                   55 non-null     object
 4   Ice Accretion On Ship                 55 non-null     object
 5   Thickness of Ice Accretion On Ship    55 non-null     object
 6   Rate of Ice Accretion on Ship         55 non-null     object
 7   Sea Level Pressure                    55 non-null     object
 8   Characteristics of Pressure Tendency  55 non-null     object
 9   Pressure Tendency                     55 non-null     object
 10  Air Temperature                       55 non-null     object
 11  Wet Bulb Temperature                  55 non-null     object
 12  Dew Point Temperature                 55 non-null     object
 13  Sea Surface Temperature               55 non-null     object
 14  Wave Direction                        55 non-null     object
 15  Wave Period                           55 non-null     object
 16  Wave Height                           55 non-null     object
 17  Swell Direction                       55 non-null     object
 18  Swell Period                          55 non-null     object
 19  Swell Height                          55 non-null     object
 20  Total Cloud Amount                    55 non-null     object
 21  Low Cloud Amount                      55 non-null     object
 22  Low Cloud Type                        55 non-null     object
 23  Cloud Height Indicator                55 non-null     object
 24  Cloud Height                          55 non-null     object
 25  Middle Cloud Type                     55 non-null     object
 26  High Cloud Type                       55 non-null     object
 27  Visibility                            55 non-null     int64
 28  Visibility Indicator                  55 non-null     object
 29  Present Weather                       55 non-null     object
 30  Past Weather                          55 non-null     object
 31  Wind Direction                        55 non-null     int64
 32  Wind Speed                            55 non-null     int64
dtypes: float64(2), int64(3), object(28)
memory usage: 14.3+ KB

In [15]:
df.isnull().sum()

Identification                          0
Latitude                                0
Longitude                               0
Time of Observation                     0
Ice Accretion On Ship                   0
Thickness of Ice Accretion On Ship      0
Rate of Ice Accretion on Ship           0
Sea Level Pressure                      0
Characteristics of Pressure Tendency    0
Pressure Tendency                       0
Air Temperature                         0
Wet Bulb Temperature                    0
Dew Point Temperature                   0
Sea Surface Temperature                 0
Wave Direction                          0
Wave Period                             0
Wave Height                             0
Swell Direction                         0
Swell Period                            0
Swell Height                            0
Total Cloud Amount                      0
Low Cloud Amount                        0
Low Cloud Type                          0
Cloud Height Indicator                  0
Cloud Height                            0
Middle Cloud Type                       0
High Cloud Type                         0
Visibility                              0
Visibility Indicator                    0
Present Weather                         0
Past Weather                            0
Wind Direction                          0
Wind Speed                              0
dtype: int64

In [19]:
df.replace(['',' '],pd.NA, inplace=True)

In [20]:
df.head()

,Identification,Latitude,Longitude,Time of Observation,Ice Accretion On Ship,Thickness of Ice Accretion On Ship,Rate of Ice Accretion on Ship,Sea Level Pressure,Characteristics of Pressure Tendency,Pressure Tendency,...,Cloud Height Indicator,Cloud Height,Middle Cloud Type,High Cloud Type,Visibility,Visibility Indicator,Present Weather,Past Weather,Wind Direction,Wind Speed
0,D5GN6,-35.8,2.9,2015-01-12T00:00:00,<NA>,<NA>,<NA>,29.83,8,0.0,...,<NA>,5,<NA>,<NA>,97,<NA>,3,2,300,139
1,D5GN6,-35.9,6.9,2015-01-12T12:00:00,<NA>,<NA>,<NA>,29.93,1,0.0,...,<NA>,2,1,A,97,<NA>,2,2,180,165
2,D5GN6,-35.9,8.6,2015-01-12T18:00:00,<NA>,<NA>,<NA>,30.02,1,0.0,...,<NA>,2,0,0,97,<NA>,2,2,170,154
3,D5GN6,-35.7,11.9,2015-01-13T06:00:00,<NA>,<NA>,<NA>,30.14,0,0.0,...,<NA>,3,0,0,98,<NA>,1,2,140,118
4,D5GN6,-35.6,13.7,2015-01-13T12:00:00,<NA>,<NA>,<NA>,30.12,8,<NA>,...,<NA>,5,7,A,98,<NA>,2,1,160,123

In [21]:
df.isnull().sum()

Identification                           0
Latitude                                 0
Longitude                                0
Time of Observation                      0
Ice Accretion On Ship                   55
Thickness of Ice Accretion On Ship      55
Rate of Ice Accretion on Ship           55
Sea Level Pressure                       1
Characteristics of Pressure Tendency     1
Pressure Tendency                        2
Air Temperature                          1
Wet Bulb Temperature                    55
Dew Point Temperature                    1
Sea Surface Temperature                 55
Wave Direction                          55
Wave Period                             27
Wave Height                             27
Swell Direction                         33
Swell Period                            35
Swell Height                            32
Total Cloud Amount                       2
Low Cloud Amount                        37
Low Cloud Type                          55
Cloud Height Indicator                  55
Cloud Height                             0
Middle Cloud Type                       16
High Cloud Type                         16
Visibility                               0
Visibility Indicator                    55
Present Weather                          3
Past Weather                             4
Wind Direction                           0
Wind Speed                               0
dtype: int64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 24 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Identification                        55 non-null     object
 1   Latitude                              55 non-null     float64
 2   Longitude                             55 non-null     float64
 3   Time of Observation                   55 non-null     object
 4   Sea Level Pressure                    54 non-null     object
 5   Characteristics of Pressure Tendency  54 non-null     object
 6   Pressure Tendency                     53 non-null     object
 7   Air Temperature                       54 non-null     object
 8   Dew Point Temperature                 54 non-null     object
 9   Wave Period                           28 non-null     object
 10  Wave Height                           28 non-null     object
 11  Swell Direction                       22 non-null     object
 12  Swell Period                          20 non-null     object
 13  Swell Height                          23 non-null     object
 14  Total Cloud Amount                    53 non-null     object
 15  Low Cloud Amount                      18 non-null     object
 16  Cloud Height                          55 non-null     object
 17  Middle Cloud Type                     39 non-null     object
 18  High Cloud Type                       39 non-null     object
 19  Visibility                            55 non-null     int64
 20  Present Weather                       52 non-null     object
 21  Past Weather                          51 non-null     object
 22  Wind Direction                        55 non-null     int64
 23  Wind Speed                            55 non-null     int64
dtypes: float64(2), int64(3), object(19)
memory usage: 10.4+ KB

##null handling

In [34]:
Nan_ratio = df.isnull().sum() / len(df)
threshold = 0.4
df_cleaned = df.dropna(axis = 1, thresh=len(df) * (1 - threshold))
df_cleaned

,Identification,Latitude,Longitude,Time of Observation,Sea Level Pressure,Characteristics of Pressure Tendency,Pressure Tendency,Air Temperature,Dew Point Temperature,Total Cloud Amount,Cloud Height,Middle Cloud Type,High Cloud Type,Visibility,Present Weather,Past Weather,Wind Direction,Wind Speed
0,D5GN6,-35.8,2.9,2015-01-12T00:00:00,29.83,8,0.0,70.5,65.5,7,5,<NA>,<NA>,97,3,2,300,139
1,D5GN6,-35.9,6.9,2015-01-12T12:00:00,29.93,1,0.0,66.2,56.1,8,2,1,A,97,2,2,180,165
2,D5GN6,-35.9,8.6,2015-01-12T18:00:00,30.02,1,0.0,61.2,48.9,8,2,0,0,97,2,2,170,154
3,D5GN6,-35.7,11.9,2015-01-13T06:00:00,30.14,0,0.0,64.6,45.0,7,3,0,0,98,1,2,140,118
4,D5GN6,-35.6,13.7,2015-01-13T12:00:00,30.12,8,<NA>,66.7,50.5,4,5,7,A,98,2,1,160,123
5,D5GN6,-35.4,15.5,2015-01-13T18:00:00,30.08,5,0.0,68.4,48.9,6,3,<NA>,<NA>,97,<NA>,<NA>,120,118
6,D5GN6,-35.3,17.1,2015-01-14T00:00:00,30.01,8,0.0,68.0,57.9,8,2,1,A,97,3,2,140,139
7,D5GN6,-35.2,18.6,2015-01-14T06:00:00,29.98,3,0.0,69.3,61.7,8,3,0,0,97,2,2,100,154
8,D5GN6,-35.2,20.3,2015-01-14T12:00:00,29.91,8,0.0,80.6,57.4,7,2,A,A,97,2,2,80,129
9,D5GN6,-35.1,21.8,2015-01-14T18:00:00,29.88,3,0.0,73.2,64.8,3,3,1,5,97,2,0,90,154
10,D5GN6,-34.5,24.8,2015-01-15T06:00:00,29.75,3,0.0,73.9,68.2,4,4,1,8,97,1,1,60,139
11,D5GN6,-34.0,26.3,2015-01-15T12:00:00,29.66,8,0.0,80.6,70.0,2,5,A,4,97,1,0,70,139
12,D5GN6,-33.4,27.5,2015-01-15T18:00:00,29.54,8,0.0,75.6,70.3,6,4,1,8,97,92,9,60,232
13,D5GN6,-32.7,28.5,2015-01-16T00:00:00,29.59,8,0.0,75.2,68.5,<NA>,A,<NA>,<NA>,97,2,0,50,154
14,D5GN6,-31.9,29.5,2015-01-16T06:00:00,<NA>,<NA>,<NA>,79.3,<NA>,1,9,<NA>,<NA>,98,<NA>,<NA>,20,87
15,D5GN6,-30.9,30.4,2015-01-16T12:00:00,29.53,8,0.0,82.4,73.2,1,5,A,A,97,2,0,50,93
16,D5GN6,-29.9,31.3,2015-01-17T06:00:00,29.97,1,0.0,76.1,57.2,4,3,<NA>,<NA>,97,<NA>,<NA>,240,180
17,D5GN6,-29.5,32.7,2015-01-20T12:00:00,30.06,7,0.0,75.2,57.4,7,5,7,A,98,3,2,170,103
18,D5GN6,-28.8,36.2,2015-01-21T00:00:00,30.05,7,0.0,72.3,56.3,1,A,<NA>,<NA>,98,2,0,130,67
19,D5GN6,-28.4,38.1,2015-01-21T06:00:00,30.08,2,0.0,76.1,56.7,3,5,7,0,98,3,0,160,72
20,D5GN6,-28.0,39.8,2015-01-21T12:00:00,30.03,8,0.0,77.0,59.0,4,5,6,A,98,2,1,170,77
21,D5GN6,-27.7,41.4,2015-01-21T18:00:00,30.06,2,0.0,75.2,62.2,3,A,7,A,98,3,0,130,103
22,D5GN6,-27.4,42.9,2015-01-22T00:00:00,30.03,7,0.0,75.2,58.5,1,A,<NA>,<NA>,98,2,0,140,77
23,D5GN6,-27.0,44.6,2015-01-22T06:00:00,30.06,1,0.0,80.6,57.9,6,5,7,0,98,3,2,130,103
24,D5GN6,-26.4,46.0,2015-01-22T13:00:00,30.00,7,0.0,78.8,63.3,2,A,<NA>,<NA>,97,2,<NA>,140,113
25,D5GN6,-25.6,47.8,2015-01-22T18:00:00,30.01,2,0.0,77.0,62.1,3,A,<NA>,<NA>,98,3,0,120,113
26,D5GN6,-24.8,49.5,2015-01-23T00:00:00,29.96,6,0.0,75.2,61.3,5,A,<NA>,<NA>,98,3,2,130,113
27,D5GN6,-23.9,51.2,2015-01-23T06:00:00,29.95,0,0.0,82.2,61.7,6,6,7,0,97,3,2,110,123
28,D5GN6,-22.5,54.2,2015-01-23T18:00:00,29.87,0,0.0,78.8,68.2,4,A,<NA>,<NA>,98,3,0,150,159
29,D5GN6,-21.7,55.8,2015-01-24T00:00:00,29.79,6,0.0,77.9,73.4,8,A,<NA>,<NA>,97,62,0,140,165
30,D5GN6,-20.8,57.4,2015-01-24T06:00:00,29.84,0,0.0,84.2,74.1,6,3,7,1,98,80,1,70,87
31,D5GN6,-20.1,59.0,2015-01-24T12:00:00,29.83,7,0.0,82.4,69.4,<NA>,A,A,8,98,1,0,90,113
32,D5GN6,-19.3,60.5,2015-01-24T18:00:00,29.88,0,0.0,81.0,71.1,3,A,<NA>,<NA>,98,3,0,90,139
33,D5GN6,-18.5,62.0,2015-01-25T00:00:00,29.85,5,0.0,77.5,67.8,3,A,<NA>,<NA>,98,2,0,110,129
34,D5GN6,-17.8,63.4,2015-01-25T06:00:00,29.88,0,0.0,84.2,71.2,3,4,0,0,98,3,0,110,139
35,D5GN6,-17.0,64.9,2015-01-25T12:00:00,29.82,5,0.0,82.4,70.7,8,3,0,0,98,2,2,150,108
36,D5GN6,-16.2,66.5,2015-01-25T18:00:00,29.87,1,0.0,78.4,73.6,8,A,<NA>,<NA>,97,80,2,130,41
37,D5GN6,-14.7,69.4,2015-01-26T06:00:00,29.81,3,0.0,82.8,68.0,4,3,6,0,98,1,1,20,82
38,D5GN6,-13.2,72.2,2015-01-26T18:00:00,29.83,1,0.0,81.0,73.4,7,3,A,A,97,80,2,300,57
39,D5GN6,-12.4,73.7,2015-01-27T00:00:00,29.75,5,0.0,78.1,70.7,8,3,A,A,97,82,2,290,185
40,D5GN6,-11.6,75.2,2015-01-27T06:00:00,29.82,0,0.0,70.7,60.8,8,3,2,A,97,90,2,320,103
41,D5GN6,-10.8,76.7,2015-01-27T12:00:00,29.76,5,0.0,<NA>,73.4,1,3,7,8,97,2,2,20,463
42,D5GN6,-8.9,79.2,2015-01-28T00:00:00,29.78,3,0.0,81.5,72.0,7,5,7,0,98,2,2,340,51
43,D5GN6,-7.9,80.3,2015-01-28T06:00:00,29.84,0,0.0,82.9,72.1,5,5,7,0,98,3,0,330,31
44,D5GN6,-6.6,81.6,2015-01-28T12:00:00,29.78,3,0.0,83.3,68.0,3,4,0,0,98,2,0,310,10
45,D5GN6,-5.4,82.8,2015-01-28T18:00:00,29.86,0,0.0,81.0,70.2,3,4,A,A,98,3,0,270,26
46,D5GN6,-4.2,84.0,2015-01-29T00:00:00,29.82,3,0.0,80.4,72.1,2,3,0,0,98,3,0,90,10
47,D5GN6,-2.3,86.0,2015-01-29T12:00:00,29.83,0,0.0,84.0,73.6,2,3,0,0,98,2,0,190,26
48,D5GN6,-0.2,88.1,2015-01-30T00:00:00,29.87,3,0.0,79.3,67.8,3,5,0,8,98,3,0,362,10
49,D5GN6,0.8,89.2,2015-01-30T06:00:00,29.91,0,0.0,87.8,75.9,3,6,6,A,98,2,1,310,36
50,D5GN6,2.0,90.4,2015-01-30T12:00:00,29.86,3,0.0,83.1,73.2,4,3,7,0,97,3,2,330,36
51,D5GN6,3.0,91.5,2015-01-30T18:00:00,29.90,8,0.0,83.3,76.8,6,3,A,A,97,13,2,320,46
52,D5GN6,4.2,92.6,2015-01-31T00:00:00,29.85,3,0.0,80.8,71.8,6,4,3,4,98,3,1,360,57
53,D5GN6,5.2,93.6,2015-01-31T06:00:00,29.87,8,0.0,86.0,69.4,5,6,<NA>,<NA>,97,2,1,40,82
54,D5GN6,6.1,94.6,2015-01-31T12:00:00,29.80,2,0.0,82.8,75.2,3,4,8,8,97,2,0,60,87

In [35]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Identification                        55 non-null     object
 1   Latitude                              55 non-null     float64
 2   Longitude                             55 non-null     float64
 3   Time of Observation                   55 non-null     object
 4   Sea Level Pressure                    54 non-null     object
 5   Characteristics of Pressure Tendency  54 non-null     object
 6   Pressure Tendency                     53 non-null     object
 7   Air Temperature                       54 non-null     object
 8   Dew Point Temperature                 54 non-null     object
 9   Total Cloud Amount                    53 non-null     object
 10  Cloud Height                          55 non-null     object
 11  Middle Cloud Type                     39 non-null     object
 12  High Cloud Type                       39 non-null     object
 13  Visibility                            55 non-null     int64
 14  Present Weather                       52 non-null     object
 15  Past Weather                          51 non-null     object
 16  Wind Direction                        55 non-null     int64
 17  Wind Speed                            55 non-null     int64
dtypes: float64(2), int64(3), object(13)
memory usage: 7.9+ KB

In [63]:
numeric_cols = df_cleaned.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = df_cleaned.select_dtypes(include=['object', 'category']).columns

In [46]:
df_numeric = df.drop(cat_cols, axis=1)
df_cat = df.drop(numeric_cols, axis=1)

In [67]:
df_cleaned[numeric_cols] = df_cleaned[numeric_cols].fillna(df_cleaned[numeric_cols].median())
df_cleaned[categorical_cols] = df_cleaned[categorical_cols].fillna(df_cleaned[categorical_cols].mode().iloc[0])

<ipython-input-67-55d72ac3082f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[numeric_cols] = df_cleaned[numeric_cols].fillna(df_cleaned[numeric_cols].median())
<ipython-input-67-55d72ac3082f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[categorical_cols] = df_cleaned[categorical_cols].fillna(df_cleaned[categorical_cols].mode().iloc[0])

In [68]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Identification                        55 non-null     object
 1   Latitude                              55 non-null     float64
 2   Longitude                             55 non-null     float64
 3   Time of Observation                   55 non-null     object
 4   Sea Level Pressure                    55 non-null     object
 5   Characteristics of Pressure Tendency  55 non-null     object
 6   Pressure Tendency                     55 non-null     object
 7   Air Temperature                       55 non-null     object
 8   Dew Point Temperature                 55 non-null     object
 9   Total Cloud Amount                    55 non-null     object
 10  Cloud Height                          55 non-null     object
 11  Middle Cloud Type                     55 non-null     object
 12  High Cloud Type                       55 non-null     object
 13  Visibility                            55 non-null     int64
 14  Present Weather                       55 non-null     object
 15  Past Weather                          55 non-null     object
 16  Wind Direction                        55 non-null     int64
 17  Wind Speed                            55 non-null     int64
dtypes: float64(2), int64(3), object(13)
memory usage: 7.9+ KB

##Outlier handling

In [89]:
def calculate_outliers_percentage(df):
    outlier_counts = {}
    for column in df.select_dtypes(include=['number']).columns:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Calculate outliers
        outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
        outlier_counts[column] = len(outliers)

    # Print the percentage of outliers for each column
    for column in outlier_counts:
        percentage = (outlier_counts[column] / len(df)) * 100
        print(f"Percentage of outliers in {column}: {percentage:.2f}%")

# Example usage:
calculate_outliers_percentage(df_cleaned)

Percentage of outliers in Latitude: 0.00%
Percentage of outliers in Longitude: 0.00%
Percentage of outliers in Visibility: 0.00%
Percentage of outliers in Wind Direction: 0.00%
Percentage of outliers in Wind Speed: 1.82%

In [94]:
def handle_outliers(df):
    for column in numeric_cols:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Capping
        df[column] = df[column].clip(lower=lower_bound, upper=upper_bound)

    return df

# Apply to both training and test datasets
df_new = handle_outliers(df_cleaned)

In [100]:
calculate_outliers_percentage(df_new)

Percentage of outliers in Latitude: 0.00%
Percentage of outliers in Longitude: 0.00%
Percentage of outliers in Visibility: 0.00%
Percentage of outliers in Wind Direction: 0.00%
Percentage of outliers in Wind Speed: 0.00%